FROM redis:latest
MAINTAINER Jonathan Martin <jmartin2@surgeforward.com>

##
# Add conf files
# COPY redis.conf /usr/local/etc/redis/redis.conf

##
# Set port
EXPOSE 6379

##
# Run
CMD [ "redis-server" ]
