version: '2'
services:
  ### Angular Container #########################################
  angular:
    build: ./angular
    container_name: cgi-angular
    image: quay.io/surgeforward/cgi:angular
    environment:
      - NGINX_HOST=cgi.test.surgeforward.com
      - NGINX_PORT=80
    ports:
      - "80:80"

  ### DATA Container ##########################################
  data:
    container_name: cgi-data
    build: ./data
    image: quay.io/surgeforward/cgi:data
    volumes:
      - /var/lib/mysql
      - /data

  ### MySQL Container #########################################
  mysql:
    container_name: cgi-mysql
    image: quay.io/surgeforward/cgi:mysql
    volumes_from:
      - data
    environment:
      - MYSQL_DATABASE:cgi_adpq
      - MYSQL_USER:cgi_adpq_user
      - MYSQL_PASSWORD:UtcPWBk.+6wEirpez4j)P
      - MYSQL_ROOT_PASSWORD:QyzgkE]CWC(Pd7Aq9(Gmj
    volumes_from:
      - data
    ports:
      - "3306:3306"
    depends_on:
      - data


  ### Redis Container #########################################
  redis:
    container_name: cgi-redis
    build: ./redis
    image: quay.io/surgeforward/cgi:redis
    volumes_from:
      - data
    ports:
      - "6379:6379"
    depends_on:
      - data
